mtprotosender.py:228 #INFO     [2025-10-02 15:00:42,668] - telethon.network.mtprotosender - 0| Connecting to 149.154.167.51:443/TcpFull...
base_events.py:1758 #ERROR    [2025-10-02 15:00:42,743] - asyncio - 0| Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F19D386440>
